import Head from 'next/head'
import MapboxMapComponent from '@/components/mapatron/mapbox_map_component';
import MapatronSettingsMenu from '@/components/mapatron/map_settings/navbar';
import { block } from "million/react-server";

const Main = () => {
  return (
    <main id="map-page-wrap">
      <MapatronSettingsMenu />
      <MapboxMapComponent/>  
    </main>
  );
};

const MainBlock = block(Main);

// TODO, make the map itself into an component, pass key as prop or use process.env
export default function Home() {
  return (
    <>
      <Head>
        <title>Mapatron</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainBlock/>
      
    </>
  )
}
